// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtRCDbnN950UmPm0YTetttOStZHTc_F7w',
    appId: '1:368657010540:web:b33fe2da18b74ce09aed49',
    messagingSenderId: '368657010540',
    projectId: 'teste-81515',
    authDomain: 'teste-81515.firebaseapp.com',
    storageBucket: 'teste-81515.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl-3h_Cup-pXt8mjUME_5pr2geYmRdSrc',
    appId: '1:368657010540:android:e9c2fafbb708abae9aed49',
    messagingSenderId: '368657010540',
    projectId: 'teste-81515',
    storageBucket: 'teste-81515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgx-M8FLl7j9aTSZeay4mmTtvlTklG78',
    appId: '1:368657010540:ios:f7fd40b8c30623b29aed49',
    messagingSenderId: '368657010540',
    projectId: 'teste-81515',
    storageBucket: 'teste-81515.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAgx-M8FLl7j9aTSZeay4mmTtvlTklG78',
    appId: '1:368657010540:ios:6132f13bae1a506f9aed49',
    messagingSenderId: '368657010540',
    projectId: 'teste-81515',
    storageBucket: 'teste-81515.firebasestorage.app',
    iosBundleId: 'com.example.quiosqueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtRCDbnN950UmPm0YTetttOStZHTc_F7w',
    appId: '1:368657010540:web:010051b22b04425f9aed49',
    messagingSenderId: '368657010540',
    projectId: 'teste-81515',
    authDomain: 'teste-81515.firebaseapp.com',
    storageBucket: 'teste-81515.firebasestorage.app',
  );
}
